- name: recruit-project
  hosts: web
  user: vagrant
  sudo: yes

  roles:
    - common
    - git
    - httpd
    - php
    - mysql
    - phpMyAdmin
    - nodejs
    - bower
    - composer
    - ntp
