- name: be sure rpmforge repositories is installed
  yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm

- name: enable off repositories
  replace: dest=/etc/yum.repos.d/rpmforge.repo regexp="enabled *= *1" replace="enabled=0"

- name: be sure git is installed
  yum: name=git enablerepo=rpmforge-extras state=present